version: '2'
services:
    ixo-web:
        container_name: ixo-web
        image: trustlab/ixo-web:dev
        ports:
            - '80:80'
        restart: always
        logging:
            driver: 'json-file'
            options:
                max-size: '1m'
                max-file: '1'
        links:
            - block-sync
        environment:
            - PORT=80
            - REACT_APP_BLOCKCHAIN_NODE_URL=http://${IP_ADDRESS}:26657
            - REACT_APP_BLOCK_SYNC_URL=http://block-sync:8080
            - REACT_APP_IXO_WORLD_ORIGIN=http://localhost

    elysian:
        container_name: elysian
        image: trustlab/ixo-elysian:dev
        links:
            - db
            - cache
            - mq
            - pol
            - cli
            - block-sync
        environment:
            - PORT=5000
            - MONGODB_URI=mongodb://db:27017/elysian
            - MEMCACHE_URI=cache:11211
            - RABITMQ_URI=amqp://guest:guest@mq:5672?heartbeat=2
            - BLOCKCHAIN_URI_REST=http://${IP_ADDRESS}:8080/api/
            - CONFIG=/usr/src/app/config.json
            - TEMPLATE_REPO=https://api.github.com/repos/ixofoundation/schema/contents/
            - ETHEREUM_API=https://ropsten.infura.io/
            - ASYM_CYPHER=aes-256-cbc
            - ASYM_KEY=trustlab.tech
            - VALIDISSUERS=did:sov:2p19P17cr6XavfMJ8htYSS
            - NODEDID=did:sov:VVWcn41cycdCLYjrxDDgcL
        ports:
            - '5000:5000'
        restart: always
        logging:
            driver: 'json-file'
            options:
                max-size: '1m'
                max-file: '1'
        volumes:
            - ./config.json:/usr/src/app/config.json
    
    db:
        container_name: db
        image: mongo
        restart: always
        ports:
            - '27017:27017'
        volumes:
            - ./db:/data/db
            - ./backup:/backup
    
    cache:
        container_name: cache
        image: memcached:latest
        restart: always
    
    mq:
        container_name: mq
        image: rabbitmq:latest
        restart: always
    
    pol:
        container_name: pol
        image: trustlab/ixo-pol:dev
        environment:
            - RABITMQ_URI=amqp://guest:guest@mq:5672?heartbeat=2
            - BLOCKCHAIN_URI_SYNC=http://${IP_ADDRESS}:26657/broadcast_tx_sync?tx=0x
            - BLOCKCHAIN_URI_COMMIT=http://${IP_ADDRESS}:26657/broadcast_tx_commit?tx=0x
            - BLOCKCHAIN_URI_VALIDATE=http://${IP_ADDRESS}:26657/tx?hash=0x
            - POLLTIMER=3000
            - ETHEREUM_API=https://ropsten.infura.io/
        restart: always
        logging:
            driver: 'json-file'
            options:
                max-size: '1m'
                max-file: '1'
    
    cli:
        container_name: cli
        image: trustlab/ixo-cli:dev
        links:
            - block-sync
        environment:
            - MONGODB_URI=mongodb://db:27017/elysian
            - MEMCACHE_URI=cache:11211
            - BLOCKCHAIN_URI_REST=http://block-sync:8080/api/did/getByDid/
    
    block-sync:
        container_name: block-sync
        image: trustlab/ixo-block-sync:dev
        links:
            - db
        environment:
            - PORT=8080
            - MONGODB_URI=mongodb://db:27017/block-sync
            - MONGODB_URI_LOCAL=mongodb://db:27017/block-sync
            - CHAIN_URI=${IP_ADDRESS}:26657
            - BC_REST=http://${IP_ADDRESS}:1317
        restart: always
        ports:
            - '8080:8080'
        logging:
            driver: 'json-file'
            options:
                max-size: '1m'
                max-file: '1'
